In [1]:
import numpy as np

def abs(x):
    return x if x > 0 else -x

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def checkError(predicted_output):
    expected_output = [[0], [1], [1], [0]]
    for i, j in zip(expected_output, predicted_output):
        if abs(i[0] - j[0]) > 0.001:
            return True
    return False


inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
expected_output = np.array([[0], [1], [1], [0]])

epoch = 0
lr = 0.1

inputLayerNeurons = int(input("enter no of inputLayer "))
hiddenLayerNeurons = int(input("enter no of hiddenlayer "))
outputLayerNeurons = int(input("enter no of outputlayer "))


hidden_weights = []

for i in range(1, inputLayerNeurons + 1):
    hidden_weights_ind = []

    for j in range(inputLayerNeurons + 1,
                   inputLayerNeurons + hiddenLayerNeurons + 1):

        hidden_weights_ind.append(float(input('w' + str(i) + str(j))))

    hidden_weights.append(hidden_weights_ind)


output_weights = []

for i in range(inputLayerNeurons + 1,
               inputLayerNeurons + hiddenLayerNeurons + 1):

    output_weights_ind = []

    for j in range(inputLayerNeurons + hiddenLayerNeurons + 1,
                   inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1):

        output_weights_ind.append(float(input('w' + str(i) + str(j))))

    output_weights.append(output_weights_ind)


hidden_bias = []
output_bias = []

for i in range(inputLayerNeurons + 1,
               inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1):

    if i > inputLayerNeurons + hiddenLayerNeurons:
        output_bias.append(float(input("o" + str(i))))
    else:
        hidden_bias.append(float(input("o" + str(i))))


hidden_weights = np.asarray(hidden_weights)
hidden_bias = np.asarray([hidden_bias])

output_weights = np.asarray(output_weights)
output_bias = np.asarray([output_bias])


print("\nInitial Hidden Weights")
print(hidden_weights)

print("\nInitial Hidden Bias")
print(hidden_bias)

print("\nInitial Output Weights")
print(output_weights)

print("\nInitial Output Bias")
print(output_bias)


predicted_output = [[0], [0], [0], [0]]

# ONLY CHANGE: maximum number of epochs
max_epochs = 100000

# ONLY CHANGE: loop condition
while checkError(predicted_output) and epoch < max_epochs:

    epoch += 1

    hidden_layer_activation = np.dot(inputs, hidden_weights)
    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output, output_weights)
    output_layer_activation += output_bias

    predicted_output = sigmoid(output_layer_activation)

    error = expected_output - predicted_output

    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)

    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr

    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * lr

    hidden_weights += inputs.T.dot(d_hidden_layer) * lr

    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr

    # Print progress every 10000 epochs
    if epoch % 10000 == 0:
        print("Epoch:", epoch)


print("\nTotal Epochs:", epoch)

print("\nFinal Hidden Weights")
print(hidden_weights)

print("\nFinal Hidden Bias")
print(hidden_bias)

print("\nFinal Output Weights")
print(output_weights)

print("\nFinal Output Bias")
print(output_bias)

print("\nFinal Output")
print(predicted_output)

enter no of inputLayer  2
enter no of hiddenlayer  2
enter no of outputlayer  1
w13 3
w14 6
w23 4
w24 5
w35 2
w45 4
o3 1
o4 6
o5 3.93



Initial Hidden Weights
[[3. 6.]
 [4. 5.]]

Initial Hidden Bias
[[1. 6.]]

Initial Output Weights
[[2.]
 [4.]]

Initial Output Bias
[[3.93]]
Epoch: 10000
Epoch: 20000
Epoch: 30000
Epoch: 40000
Epoch: 50000
Epoch: 60000
Epoch: 70000
Epoch: 80000
Epoch: 90000
Epoch: 100000

Total Epochs: 100000

Final Hidden Weights
[[9.01236344 5.99210583]
 [9.0160955  4.97822349]]

Final Hidden Bias
[[-1.01794617  6.01768368]]

Final Output Weights
[[ 6.53572699]
 [-2.85480911]]

Final Output Bias
[[-2.9870496]]

Final Output
[[0.01630005]
 [0.66634951]
 [0.66634091]
 [0.66682686]]
